name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ssh deploy
        # You may pin to the exact commit or the version.
        # uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVKEY }}
          # Remote host
          REMOTE_HOST: linux347.unoeuro.com
          # Remote user
          REMOTE_USER: ginkru.dk
          # Remote port
          REMOTE_PORT: # optional, default is 22
          # Source directory
          SOURCE: # optional, default is
          # Target directory
          TARGET: /public_html/labs/ # optional, default is /home/REMOTE_USER/
          # Arguments to pass to rsync
          ARGS: # optional, default is -rltgoDzvO
          # An array of folder to exclude
          EXCLUDE: # optional, default is

